# Generated by Django 2.2.5 on 2019-12-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('create_at', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=64)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=64)),
                ('address1', models.CharField(blank=True, max_length=64)),
                ('address2', models.CharField(blank=True, max_length=64)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('city', models.CharField(blank=True, max_length=64)),
                ('state', models.CharField(blank=True, max_length=64)),
                ('zip_code', models.CharField(blank=True, max_length=64)),
                ('about_us', models.CharField(blank=True, max_length=500)),
                ('tw_url', models.CharField(blank=True, max_length=200)),
                ('fb_url', models.CharField(blank=True, max_length=200)),
                ('inst_url', models.CharField(blank=True, max_length=200)),
                ('pin_url', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
