# Generated by Django 2.2.5 on 2019-12-26 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0002_auto_20191226_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='imd-3.jpg', upload_to='images/product')),
                ('categ_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='categ_item', to='online_shop.Categorie')),
            ],
        ),
    ]
