# Generated by Django 2.2.5 on 2019-12-27 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('online_shop', '0004_auto_20191226_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('shopping', models.FloatField(default=0)),
                ('subtotal', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Oreder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('subtotal', models.FloatField(default=0)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('cart_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='online_shop.Cart')),
                ('product_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='online_shop.product')),
            ],
        ),
    ]
